version: '3'

networks:
    insecure_net:

volumes:
    mongo_vol:

services:
    api:
        container_name: a2_insecure_api
        build:
            context: ../
            dockerfile: deployments/api.Dockerfile
        ports:
            - "10002:10002"
        
        environment:
            MONGO_USER: ${MONGO_USER}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            MONGO_NAME: ${MONGO_NAME}
            MONGO_HOST: ${MONGO_HOST}
      
        networks:
            - insecure_net
        command: "go run main.go"
        depends_on:
            - mongodb
        external_links:
            - mongodb:mongodb

    mongodb:
        container_name: mongodb
        build:
            context: ../
            dockerfile: deployments/mongo.Dockerfile

        environment:
            MONGO_USER: ${MONGO_USER}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            MONGO_NAME: ${MONGO_NAME}
            MONGO_HOST: ${MONGO_HOST}

        ports:
          - "27017:27017"
          - "27018:27018"
        
        volumes:
            - mongo_vol:/data/db
        networks:
            - insecure_net
